### ISSUE TITLE
Tasks not found

### ISSUE THREAD

**Issue by jonoabroad** [eamelink/sbt-purescript#10]
I've created an example sbt project which contains the sbt-purescript plugin, but the task doesn't appear on the console.

The project can be found here https://github.com/jonoabroad/pure-example .

The output is in the read me of the project, the only thing of note is  `[warn] Credentials file /Users/jonoabroad/.bintray/.credentials does not exist`.

The sbt task `about` does list the purescript task as present.

**Comment by eamelink** [comment]
Thanks for trying this out and reporting this!

You need to add the following to `build.sbt`:

```
lazy val root = (project in file(".")).enablePlugins(SbtWeb)
```

Clearly bad documentation from my part. I'll update the docs when I get a chance.

**Comment by jonoabroad** [comment]
Thank you, that has fixed it.
