### ISSUE TITLE
Example Project using published stable artifacts

### ISSUE THREAD

**Issue by jonoabroad** [eamelink/sbt-purescript#9]
I could only get a project to work using the instructions for the latest version.

**Comment by eamelink** [comment]
Do you mean that using 

```
addSbtPlugin("net.eamelink.sbt" % "sbt-purescript" % "0.4.0")
```

you didn't get it to work? Can you describe what happened?

**Comment by jonoabroad** [comment]
That is correct.  I get the following error:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: net.eamelink.sbt#sbt-purescript;0.4.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      net.eamelink.sbt:sbt-purescript:0.4.0 (sbtVersion=0.13, scalaVersion=2.10)
[warn] 
sbt.ResolveException: unresolved dependency: net.eamelink.sbt#sbt-purescript;0.4.0: not found
```

**Comment by eamelink** [comment]
Hmm, that's scary. This directory doesn't seem to have the actually `ivy.xml` file anymore: http://dl.bintray.com/sbt/sbt-plugin-releases/net.eamelink.sbt/sbt-purescript/scala_2.10/sbt_0.13/0.4.0/ivys/

Even though the directory it supposedly proxies to does have it: http://dl.bintray.com/eamelink/sbt-plugins/net.eamelink.sbt/sbt-purescript/scala_2.10/sbt_0.13/0.4.0/ivys/

Maybe @jsuereth has an idea what's going on here? 

In the meantime, you can add my bintray as a resolver to `project/plugins.sbt`:

```
resolvers += Resolver.url("eamelinks bintray", url("http://dl.bintray.com/eamelink/sbt-plugins"))(Resolver.ivyStylePatterns)
```

**Comment by jonoabroad** [comment]
Excellent, that resolves the dependency.  sbt doesn't find the command :( 

I'm going to have a bit more of a play and then I'll open another ticket, if it still isn't working.
